name: npm-audit

on:
  schedule:
    - cron: '40 * * * *'

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: djmeph
          issue_labels: vulnerability
          dedupe_issues: true
